import '../models/models.dart';

class SampleData {
  SampleData._();

  static const UserProfile defaultUser = UserProfile(
    id: 'user_lady',
    name: 'Lady',
    email: 'lady@pawly.app',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    weightUnit: 'kg',
  );

  static final List<Pet> initialPets = [
    const Pet(
      id: 'pet_mochi',
      name: 'Mochi',
      animalType: 'Dog',
      breed: 'Golden Retriever',
      ageYears: 3.0,
      weightKg: 28.5,
      gender: 'Male',
      imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80',
      notes: 'Loves swimming, tennis balls, and carrots. Friendly with kids and other dogs.',
      allergies: 'Seasonal grass pollen',
      microchipNumber: '985-1410-0982-1201',
      birthday: 'April 12, 2023',
      category: 'Companion',
      nickname: 'Moch',
      favoriteFood: 'Chicken jerky & freeze-dried liver',
      favoriteToy: 'Yellow squeaky tennis ball',
      favoriteActivity: 'Beach swimming & wave chasing',
      temperament: 'Affectionate, goofy, food-motivated',
      likes: ['Beach walks', 'Chicken treats', 'Car rides', 'Belly rubs'],
      dislikes: ['Thunderstorms', 'Bath time', 'Vacuum cleaner'],
      funFact: 'Professional snack inspector who can detect a cheese wrapper from two rooms away.',
    ),
    const Pet(
      id: 'pet_luna',
      name: 'Luna',
      animalType: 'Cat',
      breed: 'British Shorthair',
      ageYears: 2.0,
      weightKg: 4.2,
      gender: 'Female',
      imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
      notes: 'Quiet window birdwatcher. Prefers salmon pate. Sensitive to vacuum cleaner noise.',
      allergies: 'None reported',
      microchipNumber: '985-1410-0982-5541',
      birthday: 'May 20, 2024',
      category: 'Companion',
      nickname: 'Lulu',
      favoriteFood: 'Wild Alaskan salmon pate',
      favoriteToy: 'Laser pointer & feather wand',
      favoriteActivity: 'Sunbeam birdwatching from the balcony',
      temperament: 'Regal, calm, selective cuddler',
      likes: ['Cardboard boxes', 'Salmon treats', 'High perches'],
      dislikes: ['Sudden door knocks', 'Car rides'],
      funFact: 'Has an internal clock that chirps precisely at 6:45 AM every morning.',
    ),
    const Pet(
      id: 'pet_milo',
      name: 'Milo',
      animalType: 'Dog',
      breed: 'Beagle',
      ageYears: 1.5,
      weightKg: 12.0,
      gender: 'Male',
      imageUrl: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800&q=80',
      notes: 'High energy scent hound. Loves puzzle feeders and agility games.',
      allergies: 'Chicken sensitivity',
      microchipNumber: '985-1410-0982-8873',
      birthday: 'March 8, 2025',
      category: 'Companion',
      nickname: 'Miles',
      favoriteFood: 'Beef marrow bone & peanut butter',
      favoriteToy: 'Scent puzzle ball',
      favoriteActivity: 'Sniffing every trail blade of grass',
      temperament: 'Curious, spirited, vocal explorer',
      likes: ['Hiking trails', 'Tug of war', 'Hide and seek'],
      dislikes: ['Rain puddles', 'Ear drops'],
      funFact: 'Can track down a hidden biscuit under three folded blankets in four seconds.',
    ),
  ];

  static final List<CareRoutine> initialRoutines = [
    const CareRoutine(
      id: 'care_1',
      petId: 'pet_mochi',
      title: 'Apoquel 16mg Allergy Dose',
      time: '08:00 AM',
      date: '2026-10-02',
      category: CareCategory.medication,
      priority: 'High',
      isCompleted: true,
      notes: 'Give with morning meal kibble.',
      recurrence: 'Daily',
      assignedTo: 'Lady (Owner)',
      completedAt: '08:12 AM',
    ),
    const CareRoutine(
      id: 'care_2',
      petId: 'pet_mochi',
      title: 'Lunch & Fresh Water Refill',
      time: '12:30 PM',
      date: '2026-10-02',
      category: CareCategory.feeding,
      priority: 'Medium',
      isCompleted: true,
      notes: '1.5 cups salmon recipe + fresh filtered water bowl.',
      recurrence: 'Daily',
      assignedTo: 'Me',
      completedAt: '12:40 PM',
    ),
    const CareRoutine(
      id: 'care_3',
      petId: 'pet_mochi',
      title: 'Evening Sunset Walk',
      time: '06:00 PM',
      date: '2026-10-02',
      category: CareCategory.exercise,
      priority: 'High',
      isCompleted: false,
      notes: '35 minutes around Oak Valley trail loop.',
      recurrence: 'Daily',
      assignedTo: 'David (Co-owner)',
    ),
    const CareRoutine(
      id: 'care_4',
      petId: 'pet_mochi',
      title: 'Coat Brushing & Paw Wipe',
      time: '08:30 PM',
      date: '2026-10-02',
      category: CareCategory.grooming,
      priority: 'Low',
      isCompleted: false,
      notes: 'Undercoat de-shedding comb + chamomile paw balm.',
      recurrence: 'Daily',
      assignedTo: 'Me',
    ),
    const CareRoutine(
      id: 'care_5',
      petId: 'pet_mochi',
      title: 'Heartworm Chewable Preventive',
      time: '09:00 AM',
      date: '2026-10-15',
      category: CareCategory.medication,
      priority: 'High',
      isCompleted: false,
      notes: 'Monthly Heartgard chew with breakfast.',
      recurrence: 'Every 30 days',
      assignedTo: 'Me',
    ),
    const CareRoutine(
      id: 'care_6',
      petId: 'pet_luna',
      title: 'Salmon Pate Lunch',
      time: '12:00 PM',
      date: '2026-10-02',
      category: CareCategory.feeding,
      priority: 'Medium',
      isCompleted: true,
      notes: 'Half can salmon pate at room temperature.',
      recurrence: 'Daily',
      assignedTo: 'Lady (Owner)',
      completedAt: '12:05 PM',
    ),
    const CareRoutine(
      id: 'care_7',
      petId: 'pet_luna',
      title: 'Cat Grass & Water Fountain Clean',
      time: '07:00 PM',
      date: '2026-10-02',
      category: CareCategory.water,
      priority: 'Low',
      isCompleted: false,
      notes: 'Refill fresh ceramic fountain.',
      recurrence: 'Daily',
      assignedTo: 'David (Co-owner)',
    ),
  ];

  static final List<Appointment> initialAppointments = [
    const Appointment(
      id: 'appt_1',
      petId: 'pet_mochi',
      date: '2026-10-12',
      time: '10:30 AM',
      purpose: 'Dermatology & Allergy Check',
      clinic: 'CityVet Wellness Center',
      vetName: 'Dr. Sarah Ramos, DVM',
      notes: 'Follow-up on seasonal paw itching and Apoquel dosage evaluation.',
      isCompleted: false,
    ),
    const Appointment(
      id: 'appt_2',
      petId: 'pet_mochi',
      date: '2026-11-20',
      time: '02:00 PM',
      purpose: 'Routine Dental Scaling & Polish',
      clinic: 'CityVet Wellness Center',
      vetName: 'Dr. Sarah Ramos, DVM',
      notes: 'Pre-anesthetic fasting required 8 hours prior.',
      isCompleted: false,
    ),
    const Appointment(
      id: 'appt_3',
      petId: 'pet_mochi',
      date: '2026-08-15',
      time: '11:00 AM',
      purpose: 'Annual Wellness Exam & Rabies Booster',
      clinic: 'CityVet Wellness Center',
      vetName: 'Dr. Sarah Ramos, DVM',
      notes: 'Heart & lungs clear. Weight optimal at 28.5 kg.',
      isCompleted: true,
    ),
  ];

  static final List<HealthEvent> initialHealthEvents = [
    const HealthEvent(
      id: 'health_1',
      petId: 'pet_mochi',
      title: 'Annual Physical & Blood Panel',
      eventType: 'Checkup',
      date: 'Aug 15, 2026',
      notes: 'Comprehensive senior blood panel all within normal biological reference intervals. Ears clean.',
      veterinarian: 'Dr. Sarah Ramos, DVM',
      clinic: 'CityVet Wellness Center',
    ),
    const HealthEvent(
      id: 'health_2',
      petId: 'pet_mochi',
      title: 'DHPP Core Vaccine Booster',
      eventType: 'Vaccination',
      date: 'Aug 15, 2026',
      notes: 'Subcutaneous injection, right shoulder. No adverse allergic reaction observed.',
      veterinarian: 'Dr. Sarah Ramos, DVM',
      clinic: 'CityVet Wellness Center',
    ),
    const HealthEvent(
      id: 'health_3',
      petId: 'pet_mochi',
      title: 'Dermatology Cytology (Left Paw)',
      eventType: 'Procedure',
      date: 'Jun 22, 2026',
      notes: 'Tape cytology revealed mild yeast overgrowth between pads. Prescribed topical mousse.',
      veterinarian: 'Dr. Marcus Vance, DVM',
      clinic: 'Oak Valley Specialty Vet',
    ),
  ];

  static final List<WeightEntry> initialWeightHistory = [
    const WeightEntry(
      id: 'wt_1',
      petId: 'pet_mochi',
      weightKg: 28.5,
      date: 'Oct 01, 2026',
      notes: 'Ideal body condition score 5/9. Perfect muscle tone.',
    ),
    const WeightEntry(
      id: 'wt_2',
      petId: 'pet_mochi',
      weightKg: 28.2,
      date: 'Aug 15, 2026',
      notes: 'Weighed during annual checkup at clinic scale.',
    ),
    const WeightEntry(
      id: 'wt_3',
      petId: 'pet_mochi',
      weightKg: 27.8,
      date: 'May 10, 2026',
      notes: 'Increased outdoor swimming activities.',
    ),
    const WeightEntry(
      id: 'wt_4',
      petId: 'pet_mochi',
      weightKg: 27.4,
      date: 'Feb 18, 2026',
      notes: 'Winter conditioning weigh-in.',
    ),
    const WeightEntry(
      id: 'wt_5',
      petId: 'pet_mochi',
      weightKg: 26.9,
      date: 'Nov 02, 2025',
      notes: 'Young adult transition.',
    ),
  ];

  static final List<VaccinationRecord> initialVaccinations = [
    const VaccinationRecord(
      id: 'vax_1',
      petId: 'pet_mochi',
      vaccineName: 'Rabies (3-Year Imrab)',
      dateAdministered: 'Aug 15, 2024',
      nextDueDate: 'Aug 15, 2027',
      veterinarian: 'Dr. Sarah Ramos, DVM',
      clinic: 'CityVet Wellness Center',
      status: VaccineStatus.current,
      notes: 'Certified 3-year municipal tag #R-88319 issued.',
    ),
    const VaccinationRecord(
      id: 'vax_2',
      petId: 'pet_mochi',
      vaccineName: 'DHPP (Distemper, Parvo)',
      dateAdministered: 'Aug 15, 2026',
      nextDueDate: 'Aug 15, 2027',
      veterinarian: 'Dr. Sarah Ramos, DVM',
      clinic: 'CityVet Wellness Center',
      status: VaccineStatus.current,
      notes: 'Core subcutaneous booster.',
    ),
    const VaccinationRecord(
      id: 'vax_3',
      petId: 'pet_mochi',
      vaccineName: 'Bordetella (Oral Kennel Cough)',
      dateAdministered: 'Apr 10, 2026',
      nextDueDate: 'Oct 10, 2026',
      veterinarian: 'Dr. Sarah Ramos, DVM',
      clinic: 'CityVet Wellness Center',
      status: VaccineStatus.dueSoon,
      notes: 'Required for daycare and beach agility classes.',
    ),
    const VaccinationRecord(
      id: 'vax_4',
      petId: 'pet_mochi',
      vaccineName: 'Leptospirosis (4-Way Serovar)',
      dateAdministered: 'May 02, 2025',
      nextDueDate: 'May 02, 2026',
      veterinarian: 'Dr. Sarah Ramos, DVM',
      clinic: 'CityVet Wellness Center',
      status: VaccineStatus.overdue,
      notes: 'Recommended booster due to stream swimming.',
    ),
  ];

  static final List<Medication> initialMedications = [
    const Medication(
      id: 'med_1',
      petId: 'pet_mochi',
      name: 'Apoquel 16mg',
      dosage: '1 tablet (16mg)',
      frequency: 'Once daily with morning meal',
      instructions: 'Administer with food during seasonal pollen peaks. Do not skip days.',
      startDate: 'Aug 01, 2026',
      endDate: 'Nov 01, 2026',
      isActive: true,
    ),
    const Medication(
      id: 'med_2',
      petId: 'pet_mochi',
      name: 'Heartgard Plus Chewable',
      dosage: '1 beef chew (51-100 lbs)',
      frequency: 'Monthly on the 1st',
      instructions: 'Give directly by hand or in food bowl. Protects against heartworm.',
      startDate: 'Jan 01, 2026',
      endDate: 'Dec 31, 2026',
      isActive: true,
    ),
    const Medication(
      id: 'med_3',
      petId: 'pet_mochi',
      name: 'Cephalexin 500mg',
      dosage: '1 capsule twice daily',
      frequency: 'Every 12 hours for 10 days',
      instructions: 'Completed antibiotic course for minor skin superficial abrasion.',
      startDate: 'May 10, 2026',
      endDate: 'May 20, 2026',
      isActive: false,
    ),
  ];

  static final List<MemoryEntry> initialMemories = [
    const MemoryEntry(
      id: 'mem_1',
      petId: 'pet_mochi',
      date: 'Aug 20, 2026',
      title: 'First Big Beach Day',
      caption: 'Mochi spent three hours trying to fight the gentle waves and brought back the biggest driftwood stick on the coast.',
      imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=800&q=80',
      milestoneType: 'Adventure',
    ),
    const MemoryEntry(
      id: 'mem_2',
      petId: 'pet_mochi',
      date: 'Apr 12, 2026',
      title: '3rd Birthday Pupcake',
      caption: 'Lady baked a dog-safe peanut butter and pumpkin cake with Greek yogurt frosting. Demolished in 12 seconds flat.',
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80',
      milestoneType: 'Birthday',
    ),
    const MemoryEntry(
      id: 'mem_3',
      petId: 'pet_mochi',
      date: 'Jan 15, 2026',
      title: 'Mastered Ring the Bell Trick',
      caption: 'Figured out he can ring the brass bell hanging by the patio door whenever he wants to inspect the backyard squirrel.',
      imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80',
      milestoneType: 'Milestone',
    ),
  ];

  static final List<DocumentItem> initialDocuments = [
    const DocumentItem(
      id: 'doc_1',
      petId: 'pet_mochi',
      title: 'Rabies Certificate & Serology Tag',
      category: 'Vaccination',
      dateAdded: 'Aug 15, 2024',
      fileType: 'PDF • 1.2 MB',
    ),
    const DocumentItem(
      id: 'doc_2',
      petId: 'pet_mochi',
      title: 'Municipal Dog License Record',
      category: 'Registration',
      dateAdded: 'Jan 10, 2026',
      fileType: 'PDF • 480 KB',
    ),
    const DocumentItem(
      id: 'doc_3',
      petId: 'pet_mochi',
      title: 'Pet Insurance Comprehensive Policy',
      category: 'Insurance',
      dateAdded: 'Apr 01, 2026',
      fileType: 'PDF • 2.8 MB',
    ),
    const DocumentItem(
      id: 'doc_4',
      petId: 'pet_mochi',
      title: 'Diagnostic Comprehensive Blood Panel',
      category: 'Lab Result',
      dateAdded: 'Aug 15, 2026',
      fileType: 'PDF • 840 KB',
    ),
  ];

  static const EmergencyCardData defaultEmergency = EmergencyCardData(
    petId: 'pet_mochi',
    emergencyContactName: 'Lady (Owner)',
    emergencyPhone: '+1 (555) 392-8821',
    preferredVetName: 'Dr. Sarah Ramos, DVM',
    preferredVetPhone: '+1 (555) 902-1144',
    preferredClinic: 'CityVet Wellness Center (24/7 Urgent Care)',
    criticalNotes: 'Seasonal grass allergy. Do not administer penicillin-derived antibiotics without vet review.',
  );

  static final List<VetPrepItem> initialVetPrep = [
    const VetPrepItem(id: 'prep_1', appointmentId: 'appt_1', text: 'Bring updated vaccination certificate', isChecked: true),
    const VetPrepItem(id: 'prep_2', appointmentId: 'appt_1', text: 'Take photo of distal paw redness for Dr. Ramos', isChecked: true),
    const VetPrepItem(id: 'prep_3', appointmentId: 'appt_1', text: 'Is the paw redness allergy-related?', isChecked: false),
    const VetPrepItem(id: 'prep_4', appointmentId: 'appt_1', text: 'Should Apoquel dosage change for autumn?', isChecked: false),
  ];

  static final List<PetMilestone> initialMilestones = [
    const PetMilestone(
      id: 'mile_1',
      petId: 'pet_mochi',
      year: '2023',
      title: 'Came Home',
      subtitle: 'Adoption day celebration with new leash & cozy bed',
      date: 'Jun 10, 2023',
      isAutomated: false,
    ),
    const PetMilestone(
      id: 'mile_2',
      petId: 'pet_mochi',
      year: '2024',
      title: 'First Beach Trip',
      subtitle: 'Discovered sand and ran through coastal shallow water',
      date: 'Aug 20, 2024',
      isAutomated: false,
    ),
    const PetMilestone(
      id: 'mile_3',
      petId: 'pet_mochi',
      year: '2025',
      title: 'Completed Core Puppy Vaccines',
      subtitle: 'Fully certified for dog parks and group adventures',
      date: 'May 02, 2025',
      isAutomated: true,
    ),
    const PetMilestone(
      id: 'mile_4',
      petId: 'pet_mochi',
      year: '2026',
      title: 'Turned 3 Years Old',
      subtitle: 'Celebrated with dog-safe peanut butter pupcake',
      date: 'Apr 12, 2026',
      isAutomated: true,
    ),
  ];

  static final List<SymptomNote> initialSymptomNotes = [
    const SymptomNote(
      id: 'sym_1',
      petId: 'pet_mochi',
      date: 'Oct 02, 2026',
      appetite: 'Good',
      energy: 'Normal',
      stool: 'Normal',
      skin: 'Mild paw redness',
      notes: 'Licking paws more than usual after afternoon grass run. Applied soothing paw balm.',
    ),
    const SymptomNote(
      id: 'sym_2',
      petId: 'pet_mochi',
      date: 'Sep 18, 2026',
      appetite: 'Good',
      energy: 'High',
      stool: 'Normal',
      skin: 'Clear',
      notes: 'Energetic after morning trail walk. Good hydration all day.',
    ),
  ];

  static final List<CareCircleMember> initialCareCircle = [
    const CareCircleMember(
      id: 'circle_1',
      name: 'Lady',
      role: 'Owner',
      email: 'lady@pawly.app',
      phone: '+1 (555) 392-8821',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      permissions: ['View pet', 'Complete routines', 'Add notes', 'View health', 'Emergency access'],
    ),
    const CareCircleMember(
      id: 'circle_2',
      name: 'David',
      role: 'Family Co-owner',
      email: 'david@pawly.app',
      phone: '+1 (555) 219-9043',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      permissions: ['View pet', 'Complete routines', 'Add notes', 'Emergency access'],
    ),
    const CareCircleMember(
      id: 'circle_3',
      name: 'Sarah',
      role: 'Pet Sitter',
      email: 'sarah.sits@example.com',
      phone: '+1 (555) 604-1189',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      permissions: ['View pet', 'Complete routines', 'Add notes'],
    ),
  ];

  static const WellnessSnapshot defaultWellness = WellnessSnapshot(
    waterCupsDrank: 3,
    waterCupsTarget: 4,
    mealsCompleted: 2,
    mealsTarget: 3,
    walkMinutes: 35,
    medicationCompleted: 1,
    medicationTarget: 2,
  );

  static final List<AdoptionPet> adoptionPets = [
    const AdoptionPet(
      id: 'adopt_1',
      name: 'Barnaby',
      species: 'Rabbit',
      breed: 'Holland Lop',
      ageYears: 1.0,
      bio: 'Gentle indoor rabbit looking for a quiet home. Litter-box trained and loves fresh Timothy hay.',
      imageUrl: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=800&q=80',
      weightKg: 1.8,
      fosterStatus: 'Available for Adoption',
    ),
    const AdoptionPet(
      id: 'adopt_2',
      name: 'Buster',
      species: 'Dog',
      breed: 'Beagle Cross',
      ageYears: 4.0,
      bio: 'Affectionate and crate-trained rescue. Gets along wonderfully with children and other companions.',
      imageUrl: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800&q=80',
      weightKg: 11.4,
      fosterStatus: 'Pending Foster Review',
    ),
  ];
}
